[general]
live_config_reload = true

[window]
opacity = 0.9
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 20000
multiplier = 3

[font]
normal = { family = "Maple Mono", style = "Regular" }
bold = { family = "Maple Mono", style = "Regular" }
italic = { family = "Maple Mono", style = "Regular" }
bold_italic = { family = "Maple Mono", style = "Regular" }
size = 16

[colors.primary]
foreground = "#fcfcfc"
background = "#000000"

[bell]
animation = "EaseOut"

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 1000

[keyboard]
bindings = [
{ key = "N", mods = "Super|Shift", action = "CreateNewWindow" },
{ key = "B", mods = "Super|Shift", action = "SpawnNewInstance" },
{ key = "V", mods = "Super|Shift", action = "ToggleFullscreen" },
{ key = "C", mods = "Super|Shift", action = "Quit" },
]
